import * as cheerio from 'cheerio';

export interface ProblemDescription {
    title: string;
    url: string;
    rating: string;
    tags: string[];
    timeLimit: string;
    memoryLimit: string;
    body: string;
}

export function parseCodeforcesDescription(html: string, payload: any): ProblemDescription {
    const $ = cheerio.load(html);
    let body = "";
    
    // Codeforces Companion captures MathJax-rendered HTML. We need to revert it back to raw $$$math$$$
    // MathJax leaves a <script type="math/tex"> tag with the original math content.
    $('script[type="math/tex"]').each(function() {
        const mathContent = $(this).text();
        $(this).replaceWith(`$$$${mathContent}$$$`);
    });
    $('script[type="math/tex; mode=display"]').each(function() {
        const mathContent = $(this).text();
        $(this).replaceWith(`$$$$$$${mathContent}$$$$$$`);
    });
    // Remove all the MathJax visual spans generated by the browser
    $('.MathJax, .MathJax_Preview, .MathJax_Display, .MJX_Assistive_MathML').remove();
    
    // Check if the HTML is wrapped in a full document or just the problem-statement
    if ($(".problem-statement").length > 0) {
        body = $(".problem-statement").first().html()?.trim() ?? "";
        // Wiroxa trick to ensure pre tags get rendered correctly as code blocks
        body = body.replace(/<pre>[\r\n]*([^]+?)[\r\n]*<\/pre>/g, "<pre><code>$1</code></pre>");
    } else {
        body = $.html();
    }

    // Attempt to extract time/memory limits if they exist in the HTML
    let timeLimit = payload.timeLimit ? (payload.timeLimit / 1000) + " seconds" : "";
    let memoryLimit = payload.memoryLimit ? payload.memoryLimit + " megabytes" : "";

    const parsedTime = $(".time-limit").first().contents().last().text().trim();
    if (parsedTime) timeLimit = parsedTime;

    const parsedMem = $(".memory-limit").first().contents().last().text().trim();
    if (parsedMem) memoryLimit = parsedMem;

    // Use payload data for title/url/rating/tags
    return {
        title: payload.name || "Codeforces Problem",
        url: payload.url || "",
        rating: payload.rating || "UNKNOWN",
        tags: payload.tags || [],
        timeLimit: timeLimit,
        memoryLimit: memoryLimit,
        body: body,
    };
}
